#############################################################################
# Makefile for building: build/qucsrflayout
# Generated by qmake (2.01a) (Qt 4.8.7) on: jeu. janv. 24 21:16:59 2019
# Project:  Qucs-RFlayout.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Qucs-RFlayout.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		element.cpp \
		eqn.cpp \
		pac.cpp \
		mcorn.cpp \
		mcoupled.cpp \
		mcross.cpp \
		mgap.cpp \
		mlin.cpp \
		mmbend.cpp \
		mopen.cpp \
		mrstub.cpp \
		mstep.cpp \
		mtee.cpp \
		mvia.cpp \
		parser.cpp \
		xycalculator.cpp \
		layoutwriter.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		element.o \
		eqn.o \
		pac.o \
		mcorn.o \
		mcoupled.o \
		mcross.o \
		mgap.o \
		mlin.o \
		mmbend.o \
		mopen.o \
		mrstub.o \
		mstep.o \
		mtee.o \
		mvia.o \
		parser.o \
		xycalculator.o \
		layoutwriter.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Qucs-RFlayout.pro
QMAKE_TARGET  = qucsrflayout
DESTDIR       = build/
TARGET        = build/qucsrflayout

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) build/ || $(MKDIR) build/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Qucs-RFlayout.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Qucs-RFlayout.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Qucs-RFlayout.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qucsrflayout1.0.0 || $(MKDIR) .tmp/qucsrflayout1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qucsrflayout1.0.0/ && $(COPY_FILE) --parents element.h eqn.h pac.h mcorn.h mcoupled.h mcross.h mgap.h mlin.h mmbend.h mopen.h mrstub.h mstep.h mtee.h mvia.h parser.h xycalculator.h layoutwriter.h mainwindow.h .tmp/qucsrflayout1.0.0/ && $(COPY_FILE) --parents main.cpp element.cpp eqn.cpp pac.cpp mcorn.cpp mcoupled.cpp mcross.cpp mgap.cpp mlin.cpp mmbend.cpp mopen.cpp mrstub.cpp mstep.cpp mtee.cpp mvia.cpp parser.cpp xycalculator.cpp layoutwriter.cpp mainwindow.cpp .tmp/qucsrflayout1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/qucsrflayout1.0.0/ && (cd `dirname .tmp/qucsrflayout1.0.0` && $(TAR) qucsrflayout1.0.0.tar qucsrflayout1.0.0 && $(COMPRESS) qucsrflayout1.0.0.tar) && $(MOVE) `dirname .tmp/qucsrflayout1.0.0`/qucsrflayout1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qucsrflayout1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: parser.h \
		eqn.h \
		element.h \
		pac.h \
		mcorn.h \
		mcross.h \
		mcoupled.h \
		mgap.h \
		mmbend.h \
		mlin.h \
		mopen.h \
		mrstub.h \
		mstep.h \
		mtee.h \
		mvia.h \
		layoutwriter.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp parser.h \
		eqn.h \
		element.h \
		pac.h \
		mcorn.h \
		mcross.h \
		mcoupled.h \
		mgap.h \
		mmbend.h \
		mlin.h \
		mopen.h \
		mrstub.h \
		mstep.h \
		mtee.h \
		mvia.h \
		xycalculator.h \
		layoutwriter.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

element.o: element.cpp element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o element.o element.cpp

eqn.o: eqn.cpp eqn.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eqn.o eqn.cpp

pac.o: pac.cpp pac.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pac.o pac.cpp

mcorn.o: mcorn.cpp mcorn.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mcorn.o mcorn.cpp

mcoupled.o: mcoupled.cpp mcoupled.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mcoupled.o mcoupled.cpp

mcross.o: mcross.cpp mcross.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mcross.o mcross.cpp

mgap.o: mgap.cpp mgap.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mgap.o mgap.cpp

mlin.o: mlin.cpp mlin.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mlin.o mlin.cpp

mmbend.o: mmbend.cpp mmbend.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mmbend.o mmbend.cpp

mopen.o: mopen.cpp mopen.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mopen.o mopen.cpp

mrstub.o: mrstub.cpp mrstub.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mrstub.o mrstub.cpp

mstep.o: mstep.cpp mstep.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mstep.o mstep.cpp

mtee.o: mtee.cpp mtee.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mtee.o mtee.cpp

mvia.o: mvia.cpp mvia.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mvia.o mvia.cpp

parser.o: parser.cpp parser.h \
		eqn.h \
		element.h \
		pac.h \
		mcorn.h \
		mcross.h \
		mcoupled.h \
		mgap.h \
		mmbend.h \
		mlin.h \
		mopen.h \
		mrstub.h \
		mstep.h \
		mtee.h \
		mvia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser.o parser.cpp

xycalculator.o: xycalculator.cpp xycalculator.h \
		eqn.h \
		element.h \
		pac.h \
		mcorn.h \
		mcross.h \
		mcoupled.h \
		mgap.h \
		mmbend.h \
		mlin.h \
		mopen.h \
		mrstub.h \
		mstep.h \
		mtee.h \
		mvia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xycalculator.o xycalculator.cpp

layoutwriter.o: layoutwriter.cpp layoutwriter.h \
		eqn.h \
		element.h \
		pac.h \
		mcorn.h \
		mcross.h \
		mcoupled.h \
		mgap.h \
		mmbend.h \
		mlin.h \
		mopen.h \
		mrstub.h \
		mstep.h \
		mtee.h \
		mvia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layoutwriter.o layoutwriter.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		parser.h \
		eqn.h \
		element.h \
		pac.h \
		mcorn.h \
		mcross.h \
		mcoupled.h \
		mgap.h \
		mmbend.h \
		mlin.h \
		mopen.h \
		mrstub.h \
		mstep.h \
		mtee.h \
		mvia.h \
		layoutwriter.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

